statsd: aggregate metrics from a chunk in batch
aiven/telegraf pull request #146
Opened 2024-10-14 16:33 UTC by ezotrank

Process all metrics in a chunk together.

This is necessary for custom Prometheus-like histogram metrics. For example, when creating an `http_response_duration_seconds` metric with buckets 1...100 and a flush interval in Telegraf set to 30 seconds, the old version of the code would process each sample separately. If a flush interval occurred, only the processed metrics would be flushed with the current timestamp. The next metrics would be flushed in the following interval with a different timestamp (+30s), causing issues with histogram calculation. In the current version, all samples are processed together.

# Required for all PRs

- [ ] Updated associated README.md.
- [ ] Wrote appropriate unit tests.
- [ ] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #

2024-10-16 09:33 UTC, RommelLayco approved these changes
lgtm. 
I just want someone with more go knowledge to also review before merging

2024-10-17 08:32 UTC, facetoe commented
We should really be making changes upstream and not in our fork. Leads to maintenance nightmare.

2024-10-17 08:33 UTC, facetoe commented
Ideally we could get these changes merged upstream and get our fork closer to head of upstream cause we are lagging.

2024-10-17 08:34 UTC, facetoe requested changes
I'm going to be really annoying and request changes here as we don't really want to be adding features to our fork that are not in upstream? At least we should try upstream first.

2024-10-17 08:38 UTC, ezotrank commented
> I'm going to be really annoying and request changes here as we don't really want to be adding features to our fork that are not in upstream? At least we should try upstream first.

We already have a nightmare to sync with upstream (https://github.com/aiven/telegraf/pull/144) :sadcat: but I agree, that things might be good for others it should be pushed to upstream, and I'm already working on it, but it needs some time...

2025-05-23 12:36 UTC, closed without merging